version: '2'
networks:
  kong-net:
    driver: bridge
services:
  kong:
    image: docker.io/bitnami/kong:2
    ports:
      - "8080:8000"
      - "8001:8001"
      - "8443:8443"
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    links:
      - accounta
      - accountb
    networks:
      - kong-net

  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
    networks:
      - kong-net

# saving account a
  accounta:
    container_name: account-a
    image: account-a
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - postgresqla
    networks:
      - kong-net

  postgresqla:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=savingdb
    networks:
      - kong-net

# saving account b
  accountb:
    container_name: account-b
    image: account-b
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE=accountb
    ports:
      - "8082:8082"
    depends_on:
      - postgresqlb
    networks:
      - kong-net

  postgresqlb:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=savingdb
    networks:
      - kong-net

volumes:
  postgresql_data:
    driver: local
