version: '2'
networks:
  kong-net:
    driver: bridge
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
    networks:
      - kong-net
  kong:
    image: docker.io/bitnami/kong:2
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    networks:
      - kong-net
  app:
    container_name: saving-app
    image: saving-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
    networks:
      - kong-net
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=savingdb
    networks:
      - kong-net
volumes:
  postgresql_data:
    driver: local
