server:
  port: 8080
spring:
  flyway:
    baselineOnMigrate: true
  datasource:
    url: jdbc:postgresql://dbpostgresql:5432/savingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
